// Regenerates src/lib/cjk-font-data.ts from the @fontsource/noto-sans-sc
// package (a dev-only dependency — never imported at runtime). Re-run this
// if the font needs updating; the generated file is what actually ships.
import { readFileSync, writeFileSync } from "node:fs";

const SOURCE = "node_modules/@fontsource/noto-sans-sc/files/noto-sans-sc-chinese-simplified-400-normal.woff";
const OUTPUT = "src/lib/cjk-font-data.ts";

const buffer = readFileSync(SOURCE);
const base64 = buffer.toString("base64");

const contents = `// Generated by scripts/generate-cjk-font-data.ts — do not edit by hand.
// Source: @fontsource/noto-sans-sc (OFL-1.1), chinese-simplified subset, weight 400.
export const CJK_FONT_BASE64 =
  "${base64}";
`;

writeFileSync(OUTPUT, contents);
console.log(`Wrote ${OUTPUT} (${(contents.length / 1024).toFixed(0)} KB)`);
